baseURL: "https://crupest.life/"
title: "crupest's life"
copyright: "CC BY-NC 4.0"

enableRobotsTXT: true

languageCode: "en"
defaultContentLanguage: "en"
hasCJKLanguage: true
enableEmoji: true

disableKinds:
  - taxonomy
  - term

frontmatter:
  lastmod: [ "lastmod", "date", "publishDate" ]

markup:
  goldmark:
    extensions:
      table: true
  highlight:
    lineNos: true
    noClasses: false

build:
  noJSConfigInAssets: true

params:
  jsopts:
    minify: false
    sourceMap: ""

