#!/usr/bin/env bash

set -e

deno --version >/dev/null 2>&1 || (
    echo "Error: failed to run deno --version."
    echo "If deno is not installed, install it with:"
    echo "  curl -fsSL https://deno.land/install.sh | sh"
    exit 1
)

CRUPEST_PROJECT_DIR="$(realpath "$(dirname "$0")/..")"
export CRUPEST_PROJECT_DIR

echo "Project Dir: $CRUPEST_PROJECT_DIR"

exec deno run -A "$CRUPEST_PROJECT_DIR/deno/service-manager/main.ts" --project-dir "$CRUPEST_PROJECT_DIR" "$@"
