alias apt-get-build-dep-arm64="apt-get build-dep -aarm64 --arch-only"
alias apt-get-build-dep-indep="apt-get build-dep --indep-only"
alias dpkg-buildpackage-arm64="CONFIG_SITE=/etc/dpkg-cross/cross-config.arm64  DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -aarm64 -Pcross,nocheck"
alias dpkg-buildpackage-arm64-build="dpkg-buildpackage-arm64 -T binary-arch"
alias dpkg-buildpackage-indep-build="dpkg-buildpackage -T binary-indep"
alias dpkg-buildpackage-clean="dpkg-buildpackage -T clean"
