alias apt-get-build-dep-arm64="apt-get build-dep -aarm64 --arch-only"
alias dpkg-buildpackage-arm64="CONFIG_SITE=/etc/dpkg-cross/cross-config.arm64  DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -aarm64 -Pcross,nocheck"
alias dpkg-buildpackage-arm64-build="dpkg-buildpackage-arm64 -T binary-arch"
alias dpkg-buildpackage-arm64-clean="dpkg-buildpackage-arm64 -T clean"
alias dpkg-buildpackage-indep="dpkg-buildpackage -T binary-indep"
alias dpkg-buildpackage-clean="dpkg-buildpackage -T clean"
