mixed-port: 7897
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
profile:
  store-selected: true

external-ui: /usr/share/metacubexd
external-ui-name: metacubexd
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip

geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
  asn: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb
geo-auto-update: true
geo-update-interval: 24

ipv6: false
unified-delay: true
global-client-fingerprint: edge

dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - https://dns.alidns.com/dns-query
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1

rules:
  - GEOSITE,github,node-select
  - GEOSITE,google,node-select
  - GEOSITE,youtube,node-select
  - GEOSITE,twitter,node-select
  - GEOSITE,facebook,node-select
  - GEOSITE,discord,node-select
  - GEOSITE,reddit,node-select
  - GEOSITE,twitch,node-select
  - GEOSITE,quora,node-select
  - GEOSITE,telegram,node-select
  - GEOSITE,imgur,node-select
  - GEOSITE,stackexchange,node-select
  - GEOSITE,onedrive,node-select
  - GEOSITE,duckduckgo,node-select
  - GEOSITE,wikimedia,node-select
  - GEOSITE,gitbook,node-select
  - GEOSITE,gitlab,node-select
  - GEOSITE,creativecommons,node-select
  - GEOSITE,archive,node-select
  - GEOSITE,matrix,node-select
  - GEOSITE,tor,node-select
  - GEOSITE,python,node-select
  - GEOSITE,ruby,node-select
  - GEOSITE,rust,node-select
  - GEOSITE,nodejs,node-select
  - GEOSITE,npmjs,node-select
  - GEOSITE,qt,node-select
  - GEOSITE,docker,node-select
  - GEOSITE,v2ray,node-select
  - GEOSITE,homebrew,node-select
  - GEOSITE,bootstrap,node-select
  - GEOSITE,heroku,node-select
  - GEOSITE,vercel,node-select
  - GEOSITE,ieee,node-select
  - GEOSITE,sci-hub,node-select
  - GEOSITE,libgen,node-select
  - DOMAIN-SUFFIX,gnu.org,node-select
  - DOMAIN-SUFFIX,nongnu.org,node-select
  - DOMAIN-SUFFIX,ietf.org,node-select
  - DOMAIN-SUFFIX,packagist.org,node-select
  - DOMAIN-SUFFIX,metacubex.one,node-select
  - MATCH,DIRECT

proxy-groups:
  - name: node-select
    type: select
    proxies:
      - auto-select
    use:
      - money

  - name: auto-select
    type: url-test
    use:
      - money
    interval: 300
    url: https://www.gstatic.com/generate_204
    filter: 日本|新加坡|香港|台湾|美国
    expected-status: 204
