services:
  debian-dev:
    pull_policy: build
    build:
      context: ./docker/debian-dev
      dockerfile: Dockerfile
      pull: true
      args:
        - USER=crupest
      tags:
        - "crupest/debian-dev:latest"
    container_name: debian-dev
    init: true
    command: [ "/bootstrap/start/code-server.bash" ]
    volumes:
      - ./data/debian-dev:/data
      - debian-dev-home:/home/crupest
    restart: on-failure:3

  timeline:
    image: crupest/timeline:latest
    pull_policy: always
    container_name: timeline
    restart: on-failure:3
    environment:
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - TIMELINE_DisableAutoBackup=true
    volumes:
      - ./data/timeline:/root/timeline

volumes:
  debian-dev-home:
