server.modules += ("mod_accesslog")
server.modules += ("mod_auth", "mod_authn_file")
server.modules += ("mod_setenv", "mod_cgi", "mod_alias")

server.document-root = "/var/www/html/"
accesslog.filename = "/dev/fd/3"

$HTTP["url"] =^ "/cgit" {
    server.document-root = "/usr/share/webapps/"
    server.indexfiles = ("cgit.cgi")
    cgi.assign = ("cgit.cgi" => "")
    mimetype.assign = ( ".css" => "text/css" )
}

alias.url += ( "/git" => "/usr/lib/git-core/git-http-backend" )
$HTTP["url"] =^ "/git" {
    cgi.assign = ("" => "")
    setenv.add-environment = (
        "GIT_PROJECT_ROOT" => "/git",
        "GIT_HTTP_EXPORT_ALL" => ""
    )
    $HTTP["querystring"] =~ "service=git-receive-pack" {
        include "git-auth.conf"
    }
    $HTTP["url"] =~ "^/git/.*/git-receive-pack$" {
        include "git-auth.conf"
    }
}
