mixed-port: 7897
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
profile:
  store-selected: true

external-ui: ui/metacubexd
external-ui-name: metacubexd
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip

geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
  asn: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb
geo-auto-update: true
geo-update-interval: 24

ipv6: false
unified-delay: true
global-client-fingerprint: edge

dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
#    - 9.9.9.11
#    - tls://1.1.1.1
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - 223.5.5.5
    - 119.29.29.29

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80]
    TLS:
      ports: [443]
    QUIC:
      ports: [443]
  skip-domain:
    - "Mijia Cloud"

rule-providers:
  cn:
    type: file
    path: has-rule
    behavior: classical
    format: text

  non-cn:
    type: file
    path: not-has-rule
    behavior: classical
    format: text

  need:
    type: file
    path: need-rule
    behavior: classical
    format: text

rules:
  - RULE-SET,cn,DIRECT
  - RULE-SET,non-cn,node-select
  - RULE-SET,need,node-select
#  - NOT,((GEOIP,CN)),node-select
  - DOMAIN-SUFFIX,gnu.org,node-select
  - DOMAIN-SUFFIX,nongnu.org,node-select
  - DOMAIN-SUFFIX,ietf.org,node-select
  - DOMAIN-SUFFIX,metacubex.one,node-select
  - DOMAIN-SUFFIX,winehq.org,node-select
  - DOMAIN-SUFFIX,freedesktop.org,node-select
  - DOMAIN-SUFFIX,eff.org,node-select
  - DOMAIN-SUFFIX,typescriptlang.org,node-select
  - DOMAIN-SUFFIX,arxiv.org,node-select
#  - MATCH,node-select
  - MATCH,DIRECT

proxy-groups:
  - name: node-select
    type: select
    proxies:
      - auto-select
    use:
      - money

  - name: auto-select
    type: url-test
    use:
      - money
    interval: 300
    url: https://www.gstatic.com/generate_204
    filter: 日本|新加坡|香港|台湾|美国
    expected-status: 204
